DO-NOTTO-DO/iOS-NOTTODO

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/AchieveAPI.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/AchieveCalendarResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/AchieveDetailResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/AchieveService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/MissionDetailResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/DetailAchievementViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/CalendarView.swift
성취뷰 월간 캘린더 API 연결했습니다.
이전 달, 다음 달로 넘어갔을때 서버 연결을 위해서 calendar뷰에서 클로저를 선언하여 현재 달의 값을 받아왔습니다.
- Resolved: #50
> [Feat] #50 - 성취뷰 캘린더 API 연결

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/DailyMissionResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/HomeAPI.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/HomeSevice.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/Cell/DetailAchievementCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/DetailAchievementViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Model/MissionListModel.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
성취뷰 디테일 API연결했습니다.
- Resolved: #48
> [Feat] #48 - 성취뷰 디테일 API 연결

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
- iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIImageView+.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/RecommendAPI.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/RecommendResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/RecommendService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/Cells/RecommendCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/Models/RecommendModel.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
추천 미션 조회 API를 연결
태그 부분 데이터는 필수라고 해서 지금 빈 값이 날아오더라도 따로 분기 처리하지 않았습니당
- Resolved: #46
> [Feat] #46 - 추천 미션 조회 API 연결

- iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Utils.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FifthOnboardingViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/FourthOnboardingViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/SecondOnboardingViewController.swift
- 온보딩 delay 
- 온보딩 버튼 글자 색상 변경 
- 월간 캘린더 날짜 색상 변경 
- Resolved: #63
> [Add] #63 - 온보딩 애니메이션 추가 

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/xcshareddata/xcschemes/iOS-NOTTODO.xcscheme
- iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
- iOS-NOTTODO/iOS-NOTTODO/Application/SceneDelegate.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
카카오 및 애플 자동 로그인 구현
로그인 정보가 유효할 경우: 스플래시 → 홈 뷰
로그인 정보가 유효하지 않을 경우: 스플래시 → 로그인 뷰
- Resolved: #77
> [Feat] 자동 로그인 구현

- iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountStackView.swift
화면이 작은 기종에서 내 정보 뷰 contentLabel이 잘리는 현상을 수정했습니다!
- Resolved: #82
> [Fix] #82 - 내 정보 뷰 코드 수정

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Application/AppDelegate.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/LogoOnboardingViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/ViewControllers/ValueOnboardingViewController.swift
온보딩 gif 추가
명언 로티 나오고 gif가 바로 실행 되어야하는데 gif 첫번째 프레임에서 gif 재생 시간(7초)만큼 딜레이 됐다가 실행되는 이슈가 있습니다...
일단 올립니다 🥹
- Resolved: #81
> [Feat] #81 - 온보딩 gif 추가

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddMission/AddMissionResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
- 낫투두 생성 API를 연결했습니다.
- 홈뷰로 이동 시 미션리스트 컬렉션뷰를 reload하고 싶었는데 바로 직전화면이 아니라 클로저 호출방법이 당장 생각나지 않습니다,, 우선 PR 올립니다!
|   낫투두 생성      |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/5a522922-5a9b-421d-b42a-07b8cf205f9b" width ="250">|
- Resolved: #100
> [Feat] #100 - 낫투두 생성 API 연결

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/AddMission/RecentMissionResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/MissionHistoryCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
- 낫투두 최근 기록 조회 API를 연결했습니다.
|     낫투두 최근 기록 조회   |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/3022d9ac-23fe-4e45-9bea-8997887b3da4" width ="250">|
- Resolved: #107
> [Feat] #107 - 낫투두 최근 기록 조회 API 연결

- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/MyInfoURL.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/NetworkConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Achieve/AchieveService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Home/HomeSevice.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendActionService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendService.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionDetailCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/Cells/MissionListCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Modal/NottodoModalViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Model/MyInfoModel.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
- 낫투두명과 상황명 위치 변경
- url 수정 
|     구현 내용     |   스크린샷   |  스크린샷   |
| :-------------: | :----------: | :----------: |
|   GIF           |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/107853954/9f8c3fdd-2c85-4313-9298-6bef1898300b" width ="250">|<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/107853954/fb491deb-c3e7-4076-a843-87589e28e902" width ="250">|
- Resolved: #112
> [Fix] #112 - 낫투두명과 상황명 위치 변경

- iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
- 로그아웃 alert 뷰 구현
|   GIF           |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/107853954/68f1e1a2-3b91-4849-b72f-d268daad221b" width ="250">|
- Resolved: #120
> [Design] #120 -  로그아웃 alert뷰 구현 

- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/KeychainUtil.swift
- iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
앞선 로그인 로직 수정 이슈에서 누락 된 부분 추가
로그인 뷰 타이틀 및 서브 타이블 수정 (QA 반영)
로그인 뷰 타이틀 줄 간격 설정
- Resolved: #124
> [Fix] 로그인 로직 수정

- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfoAccount/ViewControllers/MyInfoAccountViewController.swift
- 로그아웃 API 연결
- 탈퇴 API 연결
- Resolved: #109
> [Feat] #109 - 로그아웃 및 탈퇴 API 연결

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/Bundle+.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Base/URLConstant.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Achieve/AchieveService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/AddMission/AddMissionService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Auth/AuthService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Home/HomeSevice.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendActionService.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/Service/Recommend/RecommendService.swift
- API KEY에 base url 추가했습니다.
- Resolved: #145
> [Fix] #145 - API KEY에 baseURL 추가 및 코드 수정 

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
- iOS-NOTTODO/iOS-NOTTODO/Network/API/AddMission/AddMissionAPI.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Common/Calendar/CalendarView.swift
|   날짜 선택 토글       | <img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/882c0bfb-5b6c-48e5-97a4-c4a156fa2efb" width ="250">|
- Resolved: #136
> [Feat] #136 - 생성/수정 뷰 날짜 선택 UI 및 스와이프 화면전환 시 날짜 Text 수정

- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/AchievementViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Achievement/ViewControllers/DetailAchievementViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/DetailCalendarViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/HomeViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Home/ViewControllers/MissionDetailViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Onboarding/Model/OnboardingModel.swift
- 앰플리튜드 변경사항 적용
- 불필요한 코드 삭제
- 캘린더 로직 수정
- Resolved: #150
> [Fix] #150 - 앰플리튜드 변경 사항 적용 

- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
- 텍스트필드 값 변경 시마다 토글에 전달되도록 수정
- 수정뷰 이동 시 날짜 UI 버그 수정
- Resolved: #155
> [Fix] #155 - 토글 입력값 수정

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/DefaultKeys.swift
- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/KeychainUtil.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/MyInfo/Viewcontrollers/MyInfoViewController.swift
- 카카오 유저 닉네임을 불러옵니다.
- Resolved: #157
> [Fix] #157 - 카카오 유저 닉네임 불러오기

- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
- 목표 토글 선택 위치 수정
- 날짜 선택 토글 UI 비활성화로 변경
- 한글 깨짐 현상 수정
|   토글 '선택' 위치 수정 및 한글 깨짐 현상 수정      |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/8bdfab08-c1ec-4f95-8cad-ef886d8f9dfe" width ="250">|
|   수정뷰에서 날짜 선택 UI 변경      |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/756b6a48-7f52-4bc7-902d-8e375e798c27" width ="250">|
- Resolved: #159
> [Fix] #159 - 생성/수정뷰 QA반영

- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/DateCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
- 수정하기 날짜 하루일 때 외 -1 일 hidden 처리
- 날짜 값 정렬해서 첫번째 날짜가 label에 보이도록 수정
|   수정하기 날짜 하루일 때 '외 -1 일' hidden 처리    |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/34ab63c6-cb8d-4148-91e8-2ba642e4dbe1" width ="250">|
|   날짜 값 정렬    |<img src = "https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/6a1241b3-7ca7-4995-b991-d6d7bcdd1618" width ="250">|
- Resolved: #161
> [Fix] #161 - 날짜 토글 분기처리 수정

- iOS-NOTTODO/iOS-NOTTODO/Global/Literals/Strings.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/ActionCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/GoalCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Components/AddMissionTextFieldView/AddMissionTextFieldView.swift
- 1차 출시를 위한 최종 라이팅 워싱 반영
- Resolved: #167
> [Feat] #167 - 1차 출시 최종 라이팅 워싱 반영

- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Recommend/ViewControllers/RecommendViewController.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/Cells/RecommendActionFooterView.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
추천 뷰 및 추천 상세 뷰에 앰플리튜드를 적용했습니다!
- Resolved: #174
> [Feat] #174 - 추천뷰 앰플리튜드 적용

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/NottodoCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/Cells/SituationCollectionViewCell.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
- 생성/수정뷰에 앰플리튜드 코드를 적용했습니다.
- Resolved: #169
> [Feat] #169 - 생성/수정뷰 앰플리튜드 적용

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
- DisplayName을 변경했습니다.
|   AppName 변경      | <img width="94" alt="image" src="https://github.com/DO-NOTTO-DO/iOS-NOTTODO/assets/65678579/4ac21303-1a4c-4bd5-8b73-c4c731864d16">|
- Resolved: #177
> [Chore] #177 - DisplayName 변경

- iOS-NOTTODO/iOS-NOTTODO/Presentation/RecommendAction/ViewControllers/RecommendActionViewController.swift
추천 행동 상세 뷰 앰플리튜드 수정
- Resolved: #179
> [Fix] #179 - 추천 행동 상세 뷰 앰플리튜드 수정

- iOS-NOTTODO/iOS-NOTTODO/Network/DataModel/Auth/AuthResponseDTO.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/Auth/AuthViewController.swift
- 앰플리튜드 userId 로깅 추가
- Resolved: #181
> [Feat] #181 - 앰플리튜드 userId 추가

- iOS-NOTTODO/iOS-NOTTODO.xcodeproj/project.pbxproj
수정된 라이브러리 적용했습니다.
- Resolved: #183
> [Chore] #183 - 수정된 라이브러리로 변경

- iOS-NOTTODO/iOS-NOTTODO/Global/Enum/AnalyticsEvent.swift
- iOS-NOTTODO/iOS-NOTTODO/Global/Extensions/UIImageView+.swift
- iOS-NOTTODO/iOS-NOTTODO/Presentation/AddMission/ViewControllers/AddMissionViewController.swift
앰플리튜드 complete_create_mission 누락 추가
- kingfisher 관련 extension에서 컴파일 오류가 나서 수정햇슴다..
- 모수가 적다고 해서 봤는데 누락되어있어서 코드 추가햇슴다.. 추가하다가 보니까 기획 문서에 action 타입이 배열이길래 그것도 수정했슴다
- Resolved: #187
> [Fix] #187 - 앰플리튜드 complete_create_mission 누락 추가
